### ISSUE TITLE
Request: make screens public

### ISSUE THREAD

**Issue by kjyv** [brogan89/ScreenSwipe#5]
This is probably the tiniest bug report I've ever written but could you make your screens List variable public?
Or alternatively add a public method to get the currently active screen gameObject from the list. I've changed it in a local copy so far but would be nice to include your package from the package manager again for updates etc.

And thanks for the asset, works great!

**Comment by brogan89** [comment]
I have made the screens list public as well as adding some helper functions to get current screen and any other screen from an index.

**Comment by kjyv** [comment]
Great, thanks!
