### ISSUE TITLE
Swipe doesn't work with ScrollView

### ISSUE THREAD

**Issue by ghost** [brogan89/ScreenSwipe#6]
When you have a scrollrect panel in a screen you can't swipe in that screen. My scrollView is my entire screen so there's nothing I can do about it just buttons work for moving between screens!

**Comment by ghost** [comment]
For anyone else having the same issue I used ScrollRectEx instead according to brogan post and it fixed the issue!
https://forum.unity.com/threads/screen-swipe-scroll-snap.501157/#post-3587394
Thanks!

**Comment by brogan89** [comment]
I'll add that to the read me actually. Thanks.
